name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Install Firebase
        run: npm install -g firebase-tools
      - name: Build
        run: npm run build --prod
      - name: Deploy
        run: firebase deploy --token {{secrets.FIREBASE_TOKEN}} --only hosting --non-interactive
